apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-api
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/kaungmyathan22/golang-k8s-portfolio
    targetRevision: HEAD
    path: charts/my-api # point at the chart folder

    helm:
      valueFiles:
        - values.yaml # base values
        - values-prod.yaml # environment override

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
